name: project_infinit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - mamba
  - pandas
  - scrapy
  - sqlalchemy
  - pymupdf
  - pip:
    - stanza==1.10.1
    - transformers==4.52.4
    - fuzzywuzzy==0.18.0
