name: project_infinit
channels:
  - conda-forge
dependencies:
  - feedparser
  - fuzzywuzzy
  - mamba
  - pandas
  - praw
  - psycopg2-binary
  - pymupdf
  - pytest
  - python=3.10
  - python-docx
  - python-dotenv
  - python-levenshtein
  - pyyaml
  - requests
  - scrapy
  - spacy
  - sqlalchemy
  - transformers
  - tweepy

prefix: "/home/adam/miniforge3/envs/project_infinit"
