name: project_infinit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mamba
  - pandas
  - scrapy
  - sqlalchemy
  - pymupdf
  - feedparser
  - pyyaml
  - requests
  - psycopg2-binary
  - transformers
  - spacy
  - fuzzywuzzy
  - praw
  - tweepy
  - python-dotenv
  - python-levenshtein
  - python-docx
