name: project_infinit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - mamba
  - pandas
  - scrapy
  - sqlalchemy
  - pymupdf
  - feedparser
  - pyyaml
  - requests
  - psycopg2
  - pip:
    - transformers==4.52.4
    - spacy==3.7.2
    - fuzzywuzzy==0.18.0
    - praw==7.8.0
    - tweepy==4.14.0
    - python-dotenv==1.0.0
