services:
  postgres:
    image: postgres:15
    container_name: nsm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nsm_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: "20665166"
    ports:
      - "5432:5432"
    volumes:
      - nsm_postgres_data:/var/lib/postgresql/data

volumes:
  nsm_postgres_data:
