# 游늬 scraping/sources_config.yaml
# Centralizovan치 konfigurace v코ech zdroj콢 pro web scraping
# Umo쮄갓je snadn캩j코칤 spr치vu, p콏id치v치n칤 a vyp칤n치n칤 zdroj콢

sources:
  sekty_tv:
    name: "Sekty.TV"
    description: "Specialistick칳 web o sekt치ch a n치bo쬰nsk칳ch hnut칤ch v 캛R"
    domain: "sekty.tv"
    url: "https://sekty.tv/"
    enabled: true
    selectors:
      article: "article"
      title: "h2.entry-title a::text"
      link: "h2.entry-title a::attr(href)"
      content: "div.entry-content *::text"
      author: ".author-name::text"
      date: "time::attr(datetime)"
    output_csv: "export/csv/sekty_tv_raw.csv"
    delay: 3
    retries: 3

  sekty_cz:
    name: "Sekty.cz"
    description: "Informa캜n칤 web o nov칳ch n치bo쬰nsk칳ch hnut칤ch"
    domain: "sekty.cz"
    url: "https://sekty.cz/prehled"
    enabled: true
    selectors:
      article: "div.tdb_module_loop article"
      title: "h3 a::text"
      link: "h3 a::attr(href)"
      excerpt: "div.td-excerpt::text"
      content: "div.td-post-content p::text, div.td-post-content li::text"
      author: ".td-post-author-name a::text"
      date: ".td-post-date time::attr(datetime)"
      categories: ".td-category a::text"
      tags: "ul.td-tags li a::text"
    output_csv: "export/csv/sekty_cz_raw.csv"
    delay: 3
    retries: 3

  info_dingir:
    name: "Dingir.cz"
    description: "Odborn칳 web v캩novan칳 nov칳m n치bo쬰nsk칳m hnut칤m"
    domain: "info.dingir.cz"
    url: "https://info.dingir.cz/"
    enabled: true
    selectors:
      article: "article"
      title: "h2.entry-title a::text"
      link: "h2.entry-title a::attr(href)"
      excerpt: ".entry-summary p::text"
      content: "div.entry-content p::text"
      author: ".author-name::text"
      date: "time::attr(datetime)"
    output_csv: "export/csv/info_dingir_raw.csv"
    delay: 2
    retries: 3

  pastorace:
    name: "Pastor치ln칤 p칠캜e"
    description: "캛l치nky o sekt치ch a kultech na webu Pastorace.cz"
    domain: "pastorace.cz"
    url: "https://www.pastorace.cz/Clanky/Nabozenstvi/Sekty-a-kulty"
    enabled: true
    selectors:
      article: ".article-item"
      title: "h3 a::text"
      link: "h3 a::attr(href)"
      content: ".article-content p::text"
      author: ".article-author::text"
      date: ".article-date::text"
    output_csv: "export/csv/pastorace_raw.csv"
    delay: 2
    retries: 3

  medium_seznam:
    name: "Medium.seznam.cz"
    description: "캛l치nky na st콏edn칤m port치lu Seznam"
    domain: "medium.seznam.cz"
    url: "https://medium.seznam.cz/"
    enabled: true
    selectors:
      article: "article"
      title: "h3::text"
      link: "a::attr(href)"
      excerpt: ".summary::text"
      content: "article p::text"
      author: ".author-name::text"
      date: "time::attr(datetime)"
      pagination: "a.pagination__next::attr(href)"
    output_csv: "export/csv/medium_seznam_raw.csv"
    delay: 3
    retries: 3

  soccas:
    name: "Sociologick칳 칰stav AV캛R"
    description: "Encyklopedie Sociologick칠ho 칰stavu AV 캛R"
    domain: "rg-encyklopedie.soc.cas.cz"
    url: "https://rg-encyklopedie.soc.cas.cz/index.php/Hlavn칤_strana"
    enabled: true
    selectors:
      article: "div.mw-parser-output"
      title: "h1::text"
      content: "p::text"
      links: "a::attr(href)"
    output_csv: "export/csv/soccas_raw.csv"
    delay: 3
    retries: 3

  google_news:
    name: "Google News"
    description: "Vyhled치v치n칤 zpr치v p콏es Google News (dynamicky)"
    domain: "news.google.com"
    url: "https://news.google.com/search"
    enabled: true
    type: "search_api"
    search_terms:
      - "sekta"
      - "nov칠 n치bo쬰nsk칠 hnut칤"
      - "kult"
      - "nov치 spiritu치ln칤 hnut칤"
    search_params:
      hl: "cs"
      gl: "CZ"
      ceid: "CZ:cs"
    selectors:
      article: "article"
      title: "h3::text"
      link: "a::attr(href)"
      snippet: ".PO9Qpe::text"
    output_csv: "export/csv/google_news_raw.csv"
    delay: 2
    retries: 3

  wikipedia:
    name: "Wikipedia (Czech)"
    description: "Wikipedia API pro 캜l치nky o n치bo쬰nsk칳ch hnut칤ch"
    domain: "cs.wikipedia.org"
    url: "https://cs.wikipedia.org/w/api.php"
    enabled: true
    type: "api"
    api_method: "parse"
    api_page: "Seznam_c칤rkv칤_a_n치bo쬰nsk칳ch_spole캜nost칤_v_캛esku"
    selectors:
      content: "wikitext"
    output_csv: "export/csv/wikipedia_raw.csv"
    delay: 3
    retries: 3

# Nastaven칤 glob치ln칤ho scrapingu
scraping_settings:
  user_agent: "Mozilla/5.0 (compatible; ProjectInfinit/1.0; +https://github.com/Adam8eifert/project_infinit)"
  robots_txt_obey: true
  download_delay: 2
  autothrottle_enabled: true
  autothrottle_start_delay: 1
  autothrottle_max_delay: 60
  concurrent_requests_per_domain: 1
  concurrent_requests: 1
  cookies_enabled: false
  cache_enabled: true
  cache_expiration_hours: 24

# Filtr obsahu (relevance keywords a vylou캜en칤)
content_filters:
  required_keywords:
    - "sekta"
    - "nov칠 n치bo쬰nsk칠 hnut칤"
    - "kult"
    - "spiritu치ln칤 hnut칤"
  exclude_keywords:
    - "politika"
    - "film"
    - "hudba"
    - "sport"

# Metadata pro export
metadata:
  project: "Project Infinit"
  version: "2.0"
  description: "ETL pipeline pro sb캩r a anal칳zu nov칳ch n치bo쬰nsk칳ch hnut칤 v 캛R"
  author: "Adam 만ifert"
  last_updated: "2025-11-14"
